export const OPTION_LABELS: Record<string, string> = {
  INCOME: "Khoản thu",
  EXPENSE: "Khoản chi",
  TRANSFER: "Chuyển quỹ",
  CASH: "Tiền mặt",
  BANK_TRANSFER: "Chuyển khoản",
  CARD: "Thẻ",
  EWALLET: "Ví điện tử",
  DRAFT: "Bản nháp",
  PENDING: "Chờ xử lý",
  APPROVED: "Đã duyệt",
  REJECTED: "Từ chối",
  CONFIRMED: "Đã xác nhận",
  IN_PROGRESS: "Đang thực hiện",
  COMPLETED: "Hoàn tất",
  CANCELLED: "Đã hủy",
  REVIEW: "Đang duyệt",
  DELIVERED: "Đã bàn giao",
  SENT: "Đã gửi",
  PARTIALLY_PAID: "Thanh toán một phần",
  PAID: "Đã thanh toán",
  OVERDUE: "Quá hạn",
  VOID: "Đã hủy",
  AVAILABLE: "Sẵn sàng",
  IN_USE: "Đang dùng",
  MAINTENANCE: "Bảo trì",
  BROKEN: "Hỏng",
  BOOKING: "Booking",
  PAYMENT: "Thanh toán",
  DEBT: "Công nợ",
  APPROVAL: "Duyệt chi",
  SYSTEM: "Hệ thống",
  FIXED: "Lương cố định",
  PER_PROJECT: "Theo dự án",
  HOURLY: "Theo giờ",
  true: "Có",
  false: "Không",
};

export function viOption(value: unknown) {
  return OPTION_LABELS[String(value)] ?? String(value ?? "Chưa có");
}
